name: Run Tests

on:
  pull_request:
    branches:
      - master

jobs:
  build-n-publish:
    name: Run Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install locally
        run:
          python setup.py install

      - name: Run unit tests
        run: |
          py.test
