name: Run Tests

on:
  pull_request:
    branches:
      - master

jobs:
  build-n-publish:
    name: Run Tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install HDF5
        run:
          sudo apt-get install libhdf5-serial-dev

      - name: Install locally
        run: |
          pip install -r requirements.txt
          python setup.py install

      - name: Run unit tests
        run: |
          py.test
